### ISSUE TITLE
add logging 

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/isaac-core#8]
Choose b/w

- [x] https://github.com/gabime/spdlog
- [x] https://github.com/KjellKod/g3log
- [x] https://github.com/easylogging/easyloggingpp

**Comment by agauniyal** [comment]
@jeetugalav -

spdlog looks best atm since a lot of boilerplate stuff like formatters, sinks has already been written for us and is best in benchmarks too. Easyloggingpp looks slightly dubious because of some issues opened up in their repo but provides unix signal/error handling for gcc but not for other compilers. g3log is tried and tested, has better support for threads and is fully 'crash-safe' but lacks a lot of basic features.

**Comment by jeetugalav** [comment]
According to my research and its  benchmarks   spdlog is best among all

**Comment by agauniyal** [comment]
Okay, going with spdlog :+1:

**Comment by agauniyal** [comment]
Moving to 0.4 since this won't be completed any soon.

**Comment by agauniyal** [comment]
**Tracked here** - https://github.com/mesonbuild/meson/issues/790

**Comment by agauniyal** [comment]
**PR Opened** - https://github.com/mesonbuild/spdlog/pull/1
